### ISSUE TITLE
ValueError: 'cfg.optimizer_config' undefined

### ISSUE THREAD

**Issue by 1799604432** [rampasek/GraphGPS#50]
Hi, I met this issue, and I try to change the version of torch-geometric. But it have no effect. 
 I try the version from 1.3.0 to the latest. 
Created a temporary directory at /tmp/tmpod96tla3
Writing /tmp/tmpod96tla3/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/media/tdq/25962996-51be-4a1c-89ae-bbc730928dbb/tdq/lrgb-main/main.py", line 140, in <module>
    optimizer = create_optimizer(model.parameters(),
  File "/home/tdq/anaconda3/envs/graphgps/lib/python3.10/site-packages/torch_geometric/graphgym/optim.py", line 38, in create_optimizer
    return from_config(func)(params, cfg=cfg)
  File "/home/tdq/anaconda3/envs/graphgps/lib/python3.10/site-packages/torch_geometric/graphgym/config.py", line 588, in wrapper
    raise ValueError(f"'cfg.{arg_name}' undefined")
ValueError: 'cfg.optimizer_config' undefined

**Comment by schwollie** [comment]
For me it worked when i replaced "optim:" in the config yaml files to "optimizer_config:".

**Comment by j-adamczyk** [comment]
I have the same error, did you manage to fix it?
